### ISSUE TITLE
[BUG] Summary log is showing a test as passed, but it's failed

### ISSUE THREAD

**Issue by lluuiissoo** [citihub/probr-pack-kubernetes#15]
**Describe the bug**
Follow up with @iantivey to replicate this issue.

**To Reproduce**
1. TBD

**Expected behavior**
Audit and Cucumber logs should be consistent. If one fails, the other one should reflect the same.

**Screenshots**
TBD

**Additional context**
TBD

**Comment by eddie-knight** [comment]
@lluuiissoo @iantivey
Was this related to the panic catching, or something else?

**Comment by iantivey** [comment]
I think so.  Certainly, if any dependencies fail without returning an `error` then the cucumber log will show a fail with the reason being the panic message, but the summary log shows the test has passed.
