### ISSUE TITLE
[BUG] Replicate error in podsecurity 

### ISSUE THREAD

**Issue by lluuiissoo** [citihub/probr-pack-kubernetes#24]
**Describe the bug**
An error in podsecurity was seen in one of the regression tests in demo cluster:

**Probe**: Kubernetes - podsecurity
**Scenario**: "Ensure that containers are not permitted to use ping"
**Step**: "Name": "pod creation \"succeeds\" with \"capabilities\" set to \"drop NET_RAW\" in the pod spec",
**Result**: "Failed",
**Error**: "Pod creation did not succeed: object is being deleted: pods \"podsecurity-290421-131130-30\" already exists",

**To Reproduce**
Cannot reproduce at the moment.

**Expected behavior**
No error shall occur

**Screenshots**
![image](https://user-images.githubusercontent.com/13456333/116592388-f10feb80-a8ed-11eb-9be2-3ae8050df113.png)

![image](https://user-images.githubusercontent.com/13456333/116595796-af813f80-a8f1-11eb-800d-f3cfaef4171f.png)

**Additional context**
n/a

**Comment by eddie-knight** [comment]
Seeing this alongisde my comments in #29, I have an uncomfortable suspicion that the names aren't random enough.
